### ISSUE TITLE
running benchmarks with third-party caches

### ISSUE THREAD

**Issue by tdeneau** [cache2k/cache2k-benchmark#1]
I would like to run the benchmark tests with one of the third-party configurations such as Guava or EhCache.  What are the steps necessary to do this?

**Comment by cruftex** [comment]
For the latest realse I did some modifications.

To run the benchmarks do:
git clone -b v0.21 https://github.com/headissue/cache2k-benchmark.git
cd cache2k-benchmark
mvn -Pbenchmark test

This runs all benchmarks.

If you want to run only the third party benchmarks, the util jars need to be compiled and installed.
You need a mvn install first, then you can run the tests in the thirdparty module specifically:

mvn install
cd thirdparty
mvn -Pbenchmark test

If you encounter any problems please post a error or stack trace and I will look into it. Keeping the issue open.

**Comment by cruftex** [comment]
Closing, answered some time ago :)
