### ISSUE TITLE
Integrate tCache in Benchmark

### ISSUE THREAD

**Issue by christian-esken** [cache2k/cache2k-benchmark#4]
tCache is an OpenSource Cache implementation, available on Maven Central. Here is a patch that integrates tCache into cache2k-benchmark. The integration consists of two parts:
- Factory / Benchmark classes
- Statistics creation via processJmhResults.sh

**Comment by christian-esken** [comment]
Status: The follwoing command ran succesful:
mvn -DskipTests package

**Comment by cruftex** [comment]
Also switched the license completely to Apache now.

I reorganized the copyright header of your added files since the general copyright header is provided by the maven license plugin.
